/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ua.at.shegda.patientcards.model.Indexes;
import ua.at.shegda.patientcards.model.Keys;
import ua.at.shegda.patientcards.model.Patientregsys;
import ua.at.shegda.patientcards.model.tables.records.StatusRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Status extends TableImpl<StatusRecord> {

    private static final long serialVersionUID = -1201310493;

    /**
     * The reference instance of <code>patientregsys.status</code>
     */
    public static final Status STATUS = new Status();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatusRecord> getRecordType() {
        return StatusRecord.class;
    }

    /**
     * The column <code>patientregsys.status.statuscol_ID</code>.
     */
    public final TableField<StatusRecord, Integer> STATUSCOL_ID = createField(DSL.name("statuscol_ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>patientregsys.status.statuscol_name</code>.
     */
    public final TableField<StatusRecord, String> STATUSCOL_NAME = createField(DSL.name("statuscol_name"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>patientregsys.status.statuscol_description</code>.
     */
    public final TableField<StatusRecord, String> STATUSCOL_DESCRIPTION = createField(DSL.name("statuscol_description"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>patientregsys.status</code> table reference
     */
    public Status() {
        this(DSL.name("status"), null);
    }

    /**
     * Create an aliased <code>patientregsys.status</code> table reference
     */
    public Status(String alias) {
        this(DSL.name(alias), STATUS);
    }

    /**
     * Create an aliased <code>patientregsys.status</code> table reference
     */
    public Status(Name alias) {
        this(alias, STATUS);
    }

    private Status(Name alias, Table<StatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private Status(Name alias, Table<StatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Status(Table<O> child, ForeignKey<O, StatusRecord> key) {
        super(child, key, STATUS);
    }

    @Override
    public Schema getSchema() {
        return Patientregsys.PATIENTREGSYS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STATUS_PRIMARY, Indexes.STATUS_STATUSCOL_NAME_UNIQUE);
    }

    @Override
    public Identity<StatusRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STATUS;
    }

    @Override
    public UniqueKey<StatusRecord> getPrimaryKey() {
        return Keys.KEY_STATUS_PRIMARY;
    }

    @Override
    public List<UniqueKey<StatusRecord>> getKeys() {
        return Arrays.<UniqueKey<StatusRecord>>asList(Keys.KEY_STATUS_PRIMARY, Keys.KEY_STATUS_STATUSCOL_NAME_UNIQUE);
    }

    @Override
    public Status as(String alias) {
        return new Status(DSL.name(alias), this);
    }

    @Override
    public Status as(Name alias) {
        return new Status(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Status rename(String name) {
        return new Status(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Status rename(Name name) {
        return new Status(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
