/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.enums;


import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PatientPatientcolSex implements EnumType {

    man("man"),

    woman("woman");

    private final String literal;

    private PatientPatientcolSex(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "patient_Patientcol_sex";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
