/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.daos;


import java.time.LocalDate;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ua.at.shegda.patientcards.model.tables.Doctor;
import ua.at.shegda.patientcards.model.tables.records.DoctorRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoctorDao extends DAOImpl<DoctorRecord, ua.at.shegda.patientcards.model.tables.pojos.Doctor, Integer> {

    /**
     * Create a new DoctorDao without any configuration
     */
    public DoctorDao() {
        super(Doctor.DOCTOR, ua.at.shegda.patientcards.model.tables.pojos.Doctor.class);
    }

    /**
     * Create a new DoctorDao with an attached configuration
     */
    public DoctorDao(Configuration configuration) {
        super(Doctor.DOCTOR, ua.at.shegda.patientcards.model.tables.pojos.Doctor.class, configuration);
    }

    @Override
    public Integer getId(ua.at.shegda.patientcards.model.tables.pojos.Doctor object) {
        return object.getDoctorcolId();
    }

    /**
     * Fetch records that have <code>Doctorcol_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_ID IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolId(Integer... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>Doctorcol_ID = value</code>
     */
    public ua.at.shegda.patientcards.model.tables.pojos.Doctor fetchOneByDoctorcolId(Integer value) {
        return fetchOne(Doctor.DOCTOR.DOCTORCOL_ID, value);
    }

    /**
     * Fetch records that have <code>Doctorcol_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_name IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolName(String... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_NAME, values);
    }

    /**
     * Fetch records that have <code>Doctorcol_surname BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolSurname(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_SURNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_surname IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolSurname(String... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_SURNAME, values);
    }

    /**
     * Fetch records that have <code>Doctorcol_otchestvo BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolOtchestvo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_OTCHESTVO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_otchestvo IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolOtchestvo(String... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_OTCHESTVO, values);
    }

    /**
     * Fetch records that have <code>Doctorcol_dateOfBirth BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolDateofbirth(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_DATEOFBIRTH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_dateOfBirth IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolDateofbirth(LocalDate... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_DATEOFBIRTH, values);
    }

    /**
     * Fetch records that have <code>Doctorcol_discription BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolDiscription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_DISCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_discription IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolDiscription(String... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_DISCRIPTION, values);
    }

    /**
     * Fetch records that have <code>Doctorcol_specialnost BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolSpecialnost(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_SPECIALNOST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_specialnost IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolSpecialnost(String... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_SPECIALNOST, values);
    }

    /**
     * Fetch records that have <code>Doctorcol_university BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolUniversity(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_UNIVERSITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_university IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolUniversity(String... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_UNIVERSITY, values);
    }

    /**
     * Fetch records that have <code>Doctorcol_address BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_address IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolAddress(String... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>Doctorcol_phone BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfDoctorcolPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.DOCTORCOL_PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctorcol_phone IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByDoctorcolPhone(String... values) {
        return fetch(Doctor.DOCTOR.DOCTORCOL_PHONE, values);
    }

    /**
     * Fetch records that have <code>login BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfLogin(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.LOGIN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>login IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByLogin(String... values) {
        return fetch(Doctor.DOCTOR.LOGIN, values);
    }

    /**
     * Fetch records that have <code>password BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfPassword(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.PASSWORD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByPassword(String... values) {
        return fetch(Doctor.DOCTOR.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchRangeOfType(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Doctor> fetchByType(String... values) {
        return fetch(Doctor.DOCTOR.TYPE, values);
    }
}
