/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.daos;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ua.at.shegda.patientcards.model.tables.Medicalsession;
import ua.at.shegda.patientcards.model.tables.records.MedicalsessionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicalsessionDao extends DAOImpl<MedicalsessionRecord, ua.at.shegda.patientcards.model.tables.pojos.Medicalsession, Integer> {

    /**
     * Create a new MedicalsessionDao without any configuration
     */
    public MedicalsessionDao() {
        super(Medicalsession.MEDICALSESSION, ua.at.shegda.patientcards.model.tables.pojos.Medicalsession.class);
    }

    /**
     * Create a new MedicalsessionDao with an attached configuration
     */
    public MedicalsessionDao(Configuration configuration) {
        super(Medicalsession.MEDICALSESSION, ua.at.shegda.patientcards.model.tables.pojos.Medicalsession.class, configuration);
    }

    @Override
    public Integer getId(ua.at.shegda.patientcards.model.tables.pojos.Medicalsession object) {
        return object.getMedicalsessioncolId();
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncolId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_ID IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncolId(Integer... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>MedicalSessioncol_ID = value</code>
     */
    public ua.at.shegda.patientcards.model.tables.pojos.Medicalsession fetchOneByMedicalsessioncolId(Integer value) {
        return fetchOne(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_ID, value);
    }

    /**
     * Fetch records that have <code>Patient_Patientcol_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfPatientPatientcolId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.PATIENT_PATIENTCOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Patient_Patientcol_ID IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByPatientPatientcolId(Integer... values) {
        return fetch(Medicalsession.MEDICALSESSION.PATIENT_PATIENTCOL_ID, values);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_dateRegistration BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncolDateregistration(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_DATEREGISTRATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_dateRegistration IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncolDateregistration(LocalDateTime... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_DATEREGISTRATION, values);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_dateRegistrationDown BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncolDateregistrationdown(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_DATEREGISTRATIONDOWN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_dateRegistrationDown IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncolDateregistrationdown(LocalDate... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_DATEREGISTRATIONDOWN, values);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_diagnoz BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncolDiagnoz(String lowerInclusive, String upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_DIAGNOZ, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_diagnoz IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncolDiagnoz(String... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_DIAGNOZ, values);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_medicaments BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncolMedicaments(String lowerInclusive, String upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_MEDICAMENTS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_medicaments IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncolMedicaments(String... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_MEDICAMENTS, values);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_discriptions BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncolDiscriptions(String lowerInclusive, String upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_DISCRIPTIONS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_discriptions IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncolDiscriptions(String... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_DISCRIPTIONS, values);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_positionfloor BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncolPositionfloor(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_POSITIONFLOOR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_positionfloor IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncolPositionfloor(Integer... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_POSITIONFLOOR, values);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_possitionward BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncolPossitionward(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_POSSITIONWARD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol_possitionward IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncolPossitionward(Integer... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_POSSITIONWARD, values);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol__possitionbad BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfMedicalsessioncol_Possitionbad(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL__POSSITIONBAD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MedicalSessioncol__possitionbad IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByMedicalsessioncol_Possitionbad(Integer... values) {
        return fetch(Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL__POSSITIONBAD, values);
    }

    /**
     * Fetch records that have <code>PositionBuild_PositionBuildcol_Id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfPositionbuildPositionbuildcolId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.POSITIONBUILD_POSITIONBUILDCOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PositionBuild_PositionBuildcol_Id IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByPositionbuildPositionbuildcolId(Integer... values) {
        return fetch(Medicalsession.MEDICALSESSION.POSITIONBUILD_POSITIONBUILDCOL_ID, values);
    }

    /**
     * Fetch records that have <code>Doctor_Doctorcol_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfDoctorDoctorcolId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.DOCTOR_DOCTORCOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Doctor_Doctorcol_ID IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByDoctorDoctorcolId(Integer... values) {
        return fetch(Medicalsession.MEDICALSESSION.DOCTOR_DOCTORCOL_ID, values);
    }

    /**
     * Fetch records that have <code>status_statuscol_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchRangeOfStatusStatuscolId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Medicalsession.MEDICALSESSION.STATUS_STATUSCOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status_statuscol_ID IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Medicalsession> fetchByStatusStatuscolId(Integer... values) {
        return fetch(Medicalsession.MEDICALSESSION.STATUS_STATUSCOL_ID, values);
    }
}
