/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ua.at.shegda.patientcards.model.tables.Positionbuild;
import ua.at.shegda.patientcards.model.tables.records.PositionbuildRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PositionbuildDao extends DAOImpl<PositionbuildRecord, ua.at.shegda.patientcards.model.tables.pojos.Positionbuild, Integer> {

    /**
     * Create a new PositionbuildDao without any configuration
     */
    public PositionbuildDao() {
        super(Positionbuild.POSITIONBUILD, ua.at.shegda.patientcards.model.tables.pojos.Positionbuild.class);
    }

    /**
     * Create a new PositionbuildDao with an attached configuration
     */
    public PositionbuildDao(Configuration configuration) {
        super(Positionbuild.POSITIONBUILD, ua.at.shegda.patientcards.model.tables.pojos.Positionbuild.class, configuration);
    }

    @Override
    public Integer getId(ua.at.shegda.patientcards.model.tables.pojos.Positionbuild object) {
        return object.getPositionbuildcolId();
    }

    /**
     * Fetch records that have <code>PositionBuildcol_Id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Positionbuild> fetchRangeOfPositionbuildcolId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PositionBuildcol_Id IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Positionbuild> fetchByPositionbuildcolId(Integer... values) {
        return fetch(Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PositionBuildcol_Id = value</code>
     */
    public ua.at.shegda.patientcards.model.tables.pojos.Positionbuild fetchOneByPositionbuildcolId(Integer value) {
        return fetchOne(Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_ID, value);
    }

    /**
     * Fetch records that have <code>PositionBuildcol_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Positionbuild> fetchRangeOfPositionbuildcolName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PositionBuildcol_name IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Positionbuild> fetchByPositionbuildcolName(String... values) {
        return fetch(Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>PositionBuildcol_name = value</code>
     */
    public ua.at.shegda.patientcards.model.tables.pojos.Positionbuild fetchOneByPositionbuildcolName(String value) {
        return fetchOne(Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_NAME, value);
    }
}
