/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ua.at.shegda.patientcards.model.tables.Status;
import ua.at.shegda.patientcards.model.tables.records.StatusRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusDao extends DAOImpl<StatusRecord, ua.at.shegda.patientcards.model.tables.pojos.Status, Integer> {

    /**
     * Create a new StatusDao without any configuration
     */
    public StatusDao() {
        super(Status.STATUS, ua.at.shegda.patientcards.model.tables.pojos.Status.class);
    }

    /**
     * Create a new StatusDao with an attached configuration
     */
    public StatusDao(Configuration configuration) {
        super(Status.STATUS, ua.at.shegda.patientcards.model.tables.pojos.Status.class, configuration);
    }

    @Override
    public Integer getId(ua.at.shegda.patientcards.model.tables.pojos.Status object) {
        return object.getStatuscolId();
    }

    /**
     * Fetch records that have <code>statuscol_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Status> fetchRangeOfStatuscolId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Status.STATUS.STATUSCOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>statuscol_ID IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Status> fetchByStatuscolId(Integer... values) {
        return fetch(Status.STATUS.STATUSCOL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>statuscol_ID = value</code>
     */
    public ua.at.shegda.patientcards.model.tables.pojos.Status fetchOneByStatuscolId(Integer value) {
        return fetchOne(Status.STATUS.STATUSCOL_ID, value);
    }

    /**
     * Fetch records that have <code>statuscol_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Status> fetchRangeOfStatuscolName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Status.STATUS.STATUSCOL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>statuscol_name IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Status> fetchByStatuscolName(String... values) {
        return fetch(Status.STATUS.STATUSCOL_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>statuscol_name = value</code>
     */
    public ua.at.shegda.patientcards.model.tables.pojos.Status fetchOneByStatuscolName(String value) {
        return fetchOne(Status.STATUS.STATUSCOL_NAME, value);
    }

    /**
     * Fetch records that have <code>statuscol_description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Status> fetchRangeOfStatuscolDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Status.STATUS.STATUSCOL_DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>statuscol_description IN (values)</code>
     */
    public List<ua.at.shegda.patientcards.model.tables.pojos.Status> fetchByStatuscolDescription(String... values) {
        return fetch(Status.STATUS.STATUSCOL_DESCRIPTION, values);
    }
}
