/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ua.at.shegda.patientcards.model.tables.Doctor;
import ua.at.shegda.patientcards.model.tables.Medicalsession;
import ua.at.shegda.patientcards.model.tables.Patient;
import ua.at.shegda.patientcards.model.tables.Positionbuild;
import ua.at.shegda.patientcards.model.tables.Status;


/**
 * A class modelling indexes of tables of the <code>patientregsys</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DOCTOR_PRIMARY = Indexes0.DOCTOR_PRIMARY;
    public static final Index MEDICALSESSION_FK_MEDICALSESSION_DOCTOR1_IDX = Indexes0.MEDICALSESSION_FK_MEDICALSESSION_DOCTOR1_IDX;
    public static final Index MEDICALSESSION_FK_MEDICALSESSION_PATIENT_IDX = Indexes0.MEDICALSESSION_FK_MEDICALSESSION_PATIENT_IDX;
    public static final Index MEDICALSESSION_FK_MEDICALSESSION_POSITIONBUILD1_IDX = Indexes0.MEDICALSESSION_FK_MEDICALSESSION_POSITIONBUILD1_IDX;
    public static final Index MEDICALSESSION_FK_MEDICALSESSION_STATUS1_IDX = Indexes0.MEDICALSESSION_FK_MEDICALSESSION_STATUS1_IDX;
    public static final Index MEDICALSESSION_PRIMARY = Indexes0.MEDICALSESSION_PRIMARY;
    public static final Index PATIENT_PRIMARY = Indexes0.PATIENT_PRIMARY;
    public static final Index POSITIONBUILD_POSITIONBUILDCOL_NAME_UNIQUE = Indexes0.POSITIONBUILD_POSITIONBUILDCOL_NAME_UNIQUE;
    public static final Index POSITIONBUILD_PRIMARY = Indexes0.POSITIONBUILD_PRIMARY;
    public static final Index STATUS_PRIMARY = Indexes0.STATUS_PRIMARY;
    public static final Index STATUS_STATUSCOL_NAME_UNIQUE = Indexes0.STATUS_STATUSCOL_NAME_UNIQUE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DOCTOR_PRIMARY = Internal.createIndex("PRIMARY", Doctor.DOCTOR, new OrderField[] { Doctor.DOCTOR.DOCTORCOL_ID }, true);
        public static Index MEDICALSESSION_FK_MEDICALSESSION_DOCTOR1_IDX = Internal.createIndex("fk_MedicalSession_Doctor1_idx", Medicalsession.MEDICALSESSION, new OrderField[] { Medicalsession.MEDICALSESSION.DOCTOR_DOCTORCOL_ID }, false);
        public static Index MEDICALSESSION_FK_MEDICALSESSION_PATIENT_IDX = Internal.createIndex("fk_MedicalSession_Patient_idx", Medicalsession.MEDICALSESSION, new OrderField[] { Medicalsession.MEDICALSESSION.PATIENT_PATIENTCOL_ID }, false);
        public static Index MEDICALSESSION_FK_MEDICALSESSION_POSITIONBUILD1_IDX = Internal.createIndex("fk_MedicalSession_PositionBuild1_idx", Medicalsession.MEDICALSESSION, new OrderField[] { Medicalsession.MEDICALSESSION.POSITIONBUILD_POSITIONBUILDCOL_ID }, false);
        public static Index MEDICALSESSION_FK_MEDICALSESSION_STATUS1_IDX = Internal.createIndex("fk_MedicalSession_status1_idx", Medicalsession.MEDICALSESSION, new OrderField[] { Medicalsession.MEDICALSESSION.STATUS_STATUSCOL_ID }, false);
        public static Index MEDICALSESSION_PRIMARY = Internal.createIndex("PRIMARY", Medicalsession.MEDICALSESSION, new OrderField[] { Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_ID }, true);
        public static Index PATIENT_PRIMARY = Internal.createIndex("PRIMARY", Patient.PATIENT, new OrderField[] { Patient.PATIENT.PATIENTCOL_ID }, true);
        public static Index POSITIONBUILD_POSITIONBUILDCOL_NAME_UNIQUE = Internal.createIndex("PositionBuildcol_name_UNIQUE", Positionbuild.POSITIONBUILD, new OrderField[] { Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_NAME }, true);
        public static Index POSITIONBUILD_PRIMARY = Internal.createIndex("PRIMARY", Positionbuild.POSITIONBUILD, new OrderField[] { Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_ID }, true);
        public static Index STATUS_PRIMARY = Internal.createIndex("PRIMARY", Status.STATUS, new OrderField[] { Status.STATUS.STATUSCOL_ID }, true);
        public static Index STATUS_STATUSCOL_NAME_UNIQUE = Internal.createIndex("statuscol_name_UNIQUE", Status.STATUS, new OrderField[] { Status.STATUS.STATUSCOL_NAME }, true);
    }
}
