/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ua.at.shegda.patientcards.model.tables.Doctor;
import ua.at.shegda.patientcards.model.tables.Medicalsession;
import ua.at.shegda.patientcards.model.tables.Patient;
import ua.at.shegda.patientcards.model.tables.Positionbuild;
import ua.at.shegda.patientcards.model.tables.Status;
import ua.at.shegda.patientcards.model.tables.records.DoctorRecord;
import ua.at.shegda.patientcards.model.tables.records.MedicalsessionRecord;
import ua.at.shegda.patientcards.model.tables.records.PatientRecord;
import ua.at.shegda.patientcards.model.tables.records.PositionbuildRecord;
import ua.at.shegda.patientcards.model.tables.records.StatusRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>patientregsys</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DoctorRecord, Integer> IDENTITY_DOCTOR = Identities0.IDENTITY_DOCTOR;
    public static final Identity<MedicalsessionRecord, Integer> IDENTITY_MEDICALSESSION = Identities0.IDENTITY_MEDICALSESSION;
    public static final Identity<PatientRecord, Integer> IDENTITY_PATIENT = Identities0.IDENTITY_PATIENT;
    public static final Identity<PositionbuildRecord, Integer> IDENTITY_POSITIONBUILD = Identities0.IDENTITY_POSITIONBUILD;
    public static final Identity<StatusRecord, Integer> IDENTITY_STATUS = Identities0.IDENTITY_STATUS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DoctorRecord> KEY_DOCTOR_PRIMARY = UniqueKeys0.KEY_DOCTOR_PRIMARY;
    public static final UniqueKey<MedicalsessionRecord> KEY_MEDICALSESSION_PRIMARY = UniqueKeys0.KEY_MEDICALSESSION_PRIMARY;
    public static final UniqueKey<PatientRecord> KEY_PATIENT_PRIMARY = UniqueKeys0.KEY_PATIENT_PRIMARY;
    public static final UniqueKey<PositionbuildRecord> KEY_POSITIONBUILD_PRIMARY = UniqueKeys0.KEY_POSITIONBUILD_PRIMARY;
    public static final UniqueKey<PositionbuildRecord> KEY_POSITIONBUILD_POSITIONBUILDCOL_NAME_UNIQUE = UniqueKeys0.KEY_POSITIONBUILD_POSITIONBUILDCOL_NAME_UNIQUE;
    public static final UniqueKey<StatusRecord> KEY_STATUS_PRIMARY = UniqueKeys0.KEY_STATUS_PRIMARY;
    public static final UniqueKey<StatusRecord> KEY_STATUS_STATUSCOL_NAME_UNIQUE = UniqueKeys0.KEY_STATUS_STATUSCOL_NAME_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MedicalsessionRecord, PatientRecord> FK_MEDICALSESSION_PATIENT = ForeignKeys0.FK_MEDICALSESSION_PATIENT;
    public static final ForeignKey<MedicalsessionRecord, PositionbuildRecord> FK_MEDICALSESSION_POSITIONBUILD1 = ForeignKeys0.FK_MEDICALSESSION_POSITIONBUILD1;
    public static final ForeignKey<MedicalsessionRecord, DoctorRecord> FK_MEDICALSESSION_DOCTOR1 = ForeignKeys0.FK_MEDICALSESSION_DOCTOR1;
    public static final ForeignKey<MedicalsessionRecord, StatusRecord> FK_MEDICALSESSION_STATUS1 = ForeignKeys0.FK_MEDICALSESSION_STATUS1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DoctorRecord, Integer> IDENTITY_DOCTOR = Internal.createIdentity(Doctor.DOCTOR, Doctor.DOCTOR.DOCTORCOL_ID);
        public static Identity<MedicalsessionRecord, Integer> IDENTITY_MEDICALSESSION = Internal.createIdentity(Medicalsession.MEDICALSESSION, Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_ID);
        public static Identity<PatientRecord, Integer> IDENTITY_PATIENT = Internal.createIdentity(Patient.PATIENT, Patient.PATIENT.PATIENTCOL_ID);
        public static Identity<PositionbuildRecord, Integer> IDENTITY_POSITIONBUILD = Internal.createIdentity(Positionbuild.POSITIONBUILD, Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_ID);
        public static Identity<StatusRecord, Integer> IDENTITY_STATUS = Internal.createIdentity(Status.STATUS, Status.STATUS.STATUSCOL_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DoctorRecord> KEY_DOCTOR_PRIMARY = Internal.createUniqueKey(Doctor.DOCTOR, "KEY_doctor_PRIMARY", Doctor.DOCTOR.DOCTORCOL_ID);
        public static final UniqueKey<MedicalsessionRecord> KEY_MEDICALSESSION_PRIMARY = Internal.createUniqueKey(Medicalsession.MEDICALSESSION, "KEY_medicalsession_PRIMARY", Medicalsession.MEDICALSESSION.MEDICALSESSIONCOL_ID);
        public static final UniqueKey<PatientRecord> KEY_PATIENT_PRIMARY = Internal.createUniqueKey(Patient.PATIENT, "KEY_patient_PRIMARY", Patient.PATIENT.PATIENTCOL_ID);
        public static final UniqueKey<PositionbuildRecord> KEY_POSITIONBUILD_PRIMARY = Internal.createUniqueKey(Positionbuild.POSITIONBUILD, "KEY_positionbuild_PRIMARY", Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_ID);
        public static final UniqueKey<PositionbuildRecord> KEY_POSITIONBUILD_POSITIONBUILDCOL_NAME_UNIQUE = Internal.createUniqueKey(Positionbuild.POSITIONBUILD, "KEY_positionbuild_PositionBuildcol_name_UNIQUE", Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_NAME);
        public static final UniqueKey<StatusRecord> KEY_STATUS_PRIMARY = Internal.createUniqueKey(Status.STATUS, "KEY_status_PRIMARY", Status.STATUS.STATUSCOL_ID);
        public static final UniqueKey<StatusRecord> KEY_STATUS_STATUSCOL_NAME_UNIQUE = Internal.createUniqueKey(Status.STATUS, "KEY_status_statuscol_name_UNIQUE", Status.STATUS.STATUSCOL_NAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<MedicalsessionRecord, PatientRecord> FK_MEDICALSESSION_PATIENT = Internal.createForeignKey(ua.at.shegda.patientcards.model.Keys.KEY_PATIENT_PRIMARY, Medicalsession.MEDICALSESSION, "fk_MedicalSession_Patient", Medicalsession.MEDICALSESSION.PATIENT_PATIENTCOL_ID);
        public static final ForeignKey<MedicalsessionRecord, PositionbuildRecord> FK_MEDICALSESSION_POSITIONBUILD1 = Internal.createForeignKey(ua.at.shegda.patientcards.model.Keys.KEY_POSITIONBUILD_PRIMARY, Medicalsession.MEDICALSESSION, "fk_MedicalSession_PositionBuild1", Medicalsession.MEDICALSESSION.POSITIONBUILD_POSITIONBUILDCOL_ID);
        public static final ForeignKey<MedicalsessionRecord, DoctorRecord> FK_MEDICALSESSION_DOCTOR1 = Internal.createForeignKey(ua.at.shegda.patientcards.model.Keys.KEY_DOCTOR_PRIMARY, Medicalsession.MEDICALSESSION, "fk_MedicalSession_Doctor1", Medicalsession.MEDICALSESSION.DOCTOR_DOCTORCOL_ID);
        public static final ForeignKey<MedicalsessionRecord, StatusRecord> FK_MEDICALSESSION_STATUS1 = Internal.createForeignKey(ua.at.shegda.patientcards.model.Keys.KEY_STATUS_PRIMARY, Medicalsession.MEDICALSESSION, "fk_MedicalSession_status1", Medicalsession.MEDICALSESSION.STATUS_STATUSCOL_ID);
    }
}
