/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model;


import javax.annotation.Generated;

import ua.at.shegda.patientcards.model.tables.Doctor;
import ua.at.shegda.patientcards.model.tables.Medicalsession;
import ua.at.shegda.patientcards.model.tables.Patient;
import ua.at.shegda.patientcards.model.tables.Positionbuild;
import ua.at.shegda.patientcards.model.tables.Status;


/**
 * Convenience access to all tables in patientregsys
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>patientregsys.doctor</code>.
     */
    public static final Doctor DOCTOR = Doctor.DOCTOR;

    /**
     * The table <code>patientregsys.medicalsession</code>.
     */
    public static final Medicalsession MEDICALSESSION = Medicalsession.MEDICALSESSION;

    /**
     * The table <code>patientregsys.patient</code>.
     */
    public static final Patient PATIENT = Patient.PATIENT;

    /**
     * The table <code>patientregsys.positionbuild</code>.
     */
    public static final Positionbuild POSITIONBUILD = Positionbuild.POSITIONBUILD;

    /**
     * The table <code>patientregsys.status</code>.
     */
    public static final Status STATUS = Status.STATUS;
}
