/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.records;


import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import ua.at.shegda.patientcards.model.enums.PatientPatientcolSex;
import ua.at.shegda.patientcards.model.tables.Patient;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientRecord extends UpdatableRecordImpl<PatientRecord> implements Record15<Integer, String, String, String, PatientPatientcolSex, LocalDate, String, String, String, LocalDate, String, String, String, String, String> {

    private static final long serialVersionUID = -1800990019;

    /**
     * Setter for <code>patientregsys.patient.Patientcol_ID</code>.
     */
    public void setPatientcolId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_ID</code>.
     */
    public Integer getPatientcolId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_name</code>.
     */
    public void setPatientcolName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_name</code>.
     */
    public String getPatientcolName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_surname</code>.
     */
    public void setPatientcolSurname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_surname</code>.
     */
    public String getPatientcolSurname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_otchestvo</code>.
     */
    public void setPatientcolOtchestvo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_otchestvo</code>.
     */
    public String getPatientcolOtchestvo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_sex</code>.
     */
    public void setPatientcolSex(PatientPatientcolSex value) {
        set(4, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_sex</code>.
     */
    public PatientPatientcolSex getPatientcolSex() {
        return (PatientPatientcolSex) get(4);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_dateOfBirth</code>.
     */
    public void setPatientcolDateofbirth(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_dateOfBirth</code>.
     */
    public LocalDate getPatientcolDateofbirth() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_post</code>.
     */
    public void setPatientcolPost(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_post</code>.
     */
    public String getPatientcolPost() {
        return (String) get(6);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_pasportData</code>.
     */
    public void setPatientcolPasportdata(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_pasportData</code>.
     */
    public String getPatientcolPasportdata() {
        return (String) get(7);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_numberMedPolis</code>.
     */
    public void setPatientcolNumbermedpolis(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_numberMedPolis</code>.
     */
    public String getPatientcolNumbermedpolis() {
        return (String) get(8);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_dateOutPolis</code>.
     */
    public void setPatientcolDateoutpolis(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_dateOutPolis</code>.
     */
    public LocalDate getPatientcolDateoutpolis() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_address</code>.
     */
    public void setPatientcolAddress(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_address</code>.
     */
    public String getPatientcolAddress() {
        return (String) get(10);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_phone</code>.
     */
    public void setPatientcolPhone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_phone</code>.
     */
    public String getPatientcolPhone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_email</code>.
     */
    public void setPatientcolEmail(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_email</code>.
     */
    public String getPatientcolEmail() {
        return (String) get(12);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_alergies</code>.
     */
    public void setPatientcolAlergies(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_alergies</code>.
     */
    public String getPatientcolAlergies() {
        return (String) get(13);
    }

    /**
     * Setter for <code>patientregsys.patient.Patientcol_discription</code>.
     */
    public void setPatientcolDiscription(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>patientregsys.patient.Patientcol_discription</code>.
     */
    public String getPatientcolDiscription() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Integer, String, String, String, PatientPatientcolSex, LocalDate, String, String, String, LocalDate, String, String, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, String, String, String, PatientPatientcolSex, LocalDate, String, String, String, LocalDate, String, String, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Patient.PATIENT.PATIENTCOL_ID;
    }

    @Override
    public Field<String> field2() {
        return Patient.PATIENT.PATIENTCOL_NAME;
    }

    @Override
    public Field<String> field3() {
        return Patient.PATIENT.PATIENTCOL_SURNAME;
    }

    @Override
    public Field<String> field4() {
        return Patient.PATIENT.PATIENTCOL_OTCHESTVO;
    }

    @Override
    public Field<PatientPatientcolSex> field5() {
        return Patient.PATIENT.PATIENTCOL_SEX;
    }

    @Override
    public Field<LocalDate> field6() {
        return Patient.PATIENT.PATIENTCOL_DATEOFBIRTH;
    }

    @Override
    public Field<String> field7() {
        return Patient.PATIENT.PATIENTCOL_POST;
    }

    @Override
    public Field<String> field8() {
        return Patient.PATIENT.PATIENTCOL_PASPORTDATA;
    }

    @Override
    public Field<String> field9() {
        return Patient.PATIENT.PATIENTCOL_NUMBERMEDPOLIS;
    }

    @Override
    public Field<LocalDate> field10() {
        return Patient.PATIENT.PATIENTCOL_DATEOUTPOLIS;
    }

    @Override
    public Field<String> field11() {
        return Patient.PATIENT.PATIENTCOL_ADDRESS;
    }

    @Override
    public Field<String> field12() {
        return Patient.PATIENT.PATIENTCOL_PHONE;
    }

    @Override
    public Field<String> field13() {
        return Patient.PATIENT.PATIENTCOL_EMAIL;
    }

    @Override
    public Field<String> field14() {
        return Patient.PATIENT.PATIENTCOL_ALERGIES;
    }

    @Override
    public Field<String> field15() {
        return Patient.PATIENT.PATIENTCOL_DISCRIPTION;
    }

    @Override
    public Integer component1() {
        return getPatientcolId();
    }

    @Override
    public String component2() {
        return getPatientcolName();
    }

    @Override
    public String component3() {
        return getPatientcolSurname();
    }

    @Override
    public String component4() {
        return getPatientcolOtchestvo();
    }

    @Override
    public PatientPatientcolSex component5() {
        return getPatientcolSex();
    }

    @Override
    public LocalDate component6() {
        return getPatientcolDateofbirth();
    }

    @Override
    public String component7() {
        return getPatientcolPost();
    }

    @Override
    public String component8() {
        return getPatientcolPasportdata();
    }

    @Override
    public String component9() {
        return getPatientcolNumbermedpolis();
    }

    @Override
    public LocalDate component10() {
        return getPatientcolDateoutpolis();
    }

    @Override
    public String component11() {
        return getPatientcolAddress();
    }

    @Override
    public String component12() {
        return getPatientcolPhone();
    }

    @Override
    public String component13() {
        return getPatientcolEmail();
    }

    @Override
    public String component14() {
        return getPatientcolAlergies();
    }

    @Override
    public String component15() {
        return getPatientcolDiscription();
    }

    @Override
    public Integer value1() {
        return getPatientcolId();
    }

    @Override
    public String value2() {
        return getPatientcolName();
    }

    @Override
    public String value3() {
        return getPatientcolSurname();
    }

    @Override
    public String value4() {
        return getPatientcolOtchestvo();
    }

    @Override
    public PatientPatientcolSex value5() {
        return getPatientcolSex();
    }

    @Override
    public LocalDate value6() {
        return getPatientcolDateofbirth();
    }

    @Override
    public String value7() {
        return getPatientcolPost();
    }

    @Override
    public String value8() {
        return getPatientcolPasportdata();
    }

    @Override
    public String value9() {
        return getPatientcolNumbermedpolis();
    }

    @Override
    public LocalDate value10() {
        return getPatientcolDateoutpolis();
    }

    @Override
    public String value11() {
        return getPatientcolAddress();
    }

    @Override
    public String value12() {
        return getPatientcolPhone();
    }

    @Override
    public String value13() {
        return getPatientcolEmail();
    }

    @Override
    public String value14() {
        return getPatientcolAlergies();
    }

    @Override
    public String value15() {
        return getPatientcolDiscription();
    }

    @Override
    public PatientRecord value1(Integer value) {
        setPatientcolId(value);
        return this;
    }

    @Override
    public PatientRecord value2(String value) {
        setPatientcolName(value);
        return this;
    }

    @Override
    public PatientRecord value3(String value) {
        setPatientcolSurname(value);
        return this;
    }

    @Override
    public PatientRecord value4(String value) {
        setPatientcolOtchestvo(value);
        return this;
    }

    @Override
    public PatientRecord value5(PatientPatientcolSex value) {
        setPatientcolSex(value);
        return this;
    }

    @Override
    public PatientRecord value6(LocalDate value) {
        setPatientcolDateofbirth(value);
        return this;
    }

    @Override
    public PatientRecord value7(String value) {
        setPatientcolPost(value);
        return this;
    }

    @Override
    public PatientRecord value8(String value) {
        setPatientcolPasportdata(value);
        return this;
    }

    @Override
    public PatientRecord value9(String value) {
        setPatientcolNumbermedpolis(value);
        return this;
    }

    @Override
    public PatientRecord value10(LocalDate value) {
        setPatientcolDateoutpolis(value);
        return this;
    }

    @Override
    public PatientRecord value11(String value) {
        setPatientcolAddress(value);
        return this;
    }

    @Override
    public PatientRecord value12(String value) {
        setPatientcolPhone(value);
        return this;
    }

    @Override
    public PatientRecord value13(String value) {
        setPatientcolEmail(value);
        return this;
    }

    @Override
    public PatientRecord value14(String value) {
        setPatientcolAlergies(value);
        return this;
    }

    @Override
    public PatientRecord value15(String value) {
        setPatientcolDiscription(value);
        return this;
    }

    @Override
    public PatientRecord values(Integer value1, String value2, String value3, String value4, PatientPatientcolSex value5, LocalDate value6, String value7, String value8, String value9, LocalDate value10, String value11, String value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientRecord
     */
    public PatientRecord() {
        super(Patient.PATIENT);
    }

    /**
     * Create a detached, initialised PatientRecord
     */
    public PatientRecord(Integer patientcolId, String patientcolName, String patientcolSurname, String patientcolOtchestvo, PatientPatientcolSex patientcolSex, LocalDate patientcolDateofbirth, String patientcolPost, String patientcolPasportdata, String patientcolNumbermedpolis, LocalDate patientcolDateoutpolis, String patientcolAddress, String patientcolPhone, String patientcolEmail, String patientcolAlergies, String patientcolDiscription) {
        super(Patient.PATIENT);

        set(0, patientcolId);
        set(1, patientcolName);
        set(2, patientcolSurname);
        set(3, patientcolOtchestvo);
        set(4, patientcolSex);
        set(5, patientcolDateofbirth);
        set(6, patientcolPost);
        set(7, patientcolPasportdata);
        set(8, patientcolNumbermedpolis);
        set(9, patientcolDateoutpolis);
        set(10, patientcolAddress);
        set(11, patientcolPhone);
        set(12, patientcolEmail);
        set(13, patientcolAlergies);
        set(14, patientcolDiscription);
    }
}
