/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ua.at.shegda.patientcards.model.tables.Positionbuild;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PositionbuildRecord extends UpdatableRecordImpl<PositionbuildRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1778927741;

    /**
     * Setter for <code>patientregsys.positionbuild.PositionBuildcol_Id</code>.
     */
    public void setPositionbuildcolId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>patientregsys.positionbuild.PositionBuildcol_Id</code>.
     */
    public Integer getPositionbuildcolId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>patientregsys.positionbuild.PositionBuildcol_name</code>.
     */
    public void setPositionbuildcolName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>patientregsys.positionbuild.PositionBuildcol_name</code>.
     */
    public String getPositionbuildcolName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_ID;
    }

    @Override
    public Field<String> field2() {
        return Positionbuild.POSITIONBUILD.POSITIONBUILDCOL_NAME;
    }

    @Override
    public Integer component1() {
        return getPositionbuildcolId();
    }

    @Override
    public String component2() {
        return getPositionbuildcolName();
    }

    @Override
    public Integer value1() {
        return getPositionbuildcolId();
    }

    @Override
    public String value2() {
        return getPositionbuildcolName();
    }

    @Override
    public PositionbuildRecord value1(Integer value) {
        setPositionbuildcolId(value);
        return this;
    }

    @Override
    public PositionbuildRecord value2(String value) {
        setPositionbuildcolName(value);
        return this;
    }

    @Override
    public PositionbuildRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PositionbuildRecord
     */
    public PositionbuildRecord() {
        super(Positionbuild.POSITIONBUILD);
    }

    /**
     * Create a detached, initialised PositionbuildRecord
     */
    public PositionbuildRecord(Integer positionbuildcolId, String positionbuildcolName) {
        super(Positionbuild.POSITIONBUILD);

        set(0, positionbuildcolId);
        set(1, positionbuildcolName);
    }
}
