/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ua.at.shegda.patientcards.model.tables.Status;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusRecord extends UpdatableRecordImpl<StatusRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -1105710897;

    /**
     * Setter for <code>patientregsys.status.statuscol_ID</code>.
     */
    public void setStatuscolId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>patientregsys.status.statuscol_ID</code>.
     */
    public Integer getStatuscolId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>patientregsys.status.statuscol_name</code>.
     */
    public void setStatuscolName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>patientregsys.status.statuscol_name</code>.
     */
    public String getStatuscolName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>patientregsys.status.statuscol_description</code>.
     */
    public void setStatuscolDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>patientregsys.status.statuscol_description</code>.
     */
    public String getStatuscolDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Status.STATUS.STATUSCOL_ID;
    }

    @Override
    public Field<String> field2() {
        return Status.STATUS.STATUSCOL_NAME;
    }

    @Override
    public Field<String> field3() {
        return Status.STATUS.STATUSCOL_DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getStatuscolId();
    }

    @Override
    public String component2() {
        return getStatuscolName();
    }

    @Override
    public String component3() {
        return getStatuscolDescription();
    }

    @Override
    public Integer value1() {
        return getStatuscolId();
    }

    @Override
    public String value2() {
        return getStatuscolName();
    }

    @Override
    public String value3() {
        return getStatuscolDescription();
    }

    @Override
    public StatusRecord value1(Integer value) {
        setStatuscolId(value);
        return this;
    }

    @Override
    public StatusRecord value2(String value) {
        setStatuscolName(value);
        return this;
    }

    @Override
    public StatusRecord value3(String value) {
        setStatuscolDescription(value);
        return this;
    }

    @Override
    public StatusRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusRecord
     */
    public StatusRecord() {
        super(Status.STATUS);
    }

    /**
     * Create a detached, initialised StatusRecord
     */
    public StatusRecord(Integer statuscolId, String statuscolName, String statuscolDescription) {
        super(Status.STATUS);

        set(0, statuscolId);
        set(1, statuscolName);
        set(2, statuscolDescription);
    }
}
