/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Medicalsession implements Serializable {

    private static final long serialVersionUID = -351413434;

    private Integer       medicalsessioncolId;
    private Integer       patientPatientcolId;
    private LocalDateTime medicalsessioncolDateregistration;
    private LocalDate     medicalsessioncolDateregistrationdown;
    private String        medicalsessioncolDiagnoz;
    private String        medicalsessioncolMedicaments;
    private String        medicalsessioncolDiscriptions;
    private Integer       medicalsessioncolPositionfloor;
    private Integer       medicalsessioncolPossitionward;
    private Integer       medicalsessioncol_Possitionbad;
    private Integer       positionbuildPositionbuildcolId;
    private Integer       doctorDoctorcolId;
    private Integer       statusStatuscolId;

    public Medicalsession() {}

    public Medicalsession(Medicalsession value) {
        this.medicalsessioncolId = value.medicalsessioncolId;
        this.patientPatientcolId = value.patientPatientcolId;
        this.medicalsessioncolDateregistration = value.medicalsessioncolDateregistration;
        this.medicalsessioncolDateregistrationdown = value.medicalsessioncolDateregistrationdown;
        this.medicalsessioncolDiagnoz = value.medicalsessioncolDiagnoz;
        this.medicalsessioncolMedicaments = value.medicalsessioncolMedicaments;
        this.medicalsessioncolDiscriptions = value.medicalsessioncolDiscriptions;
        this.medicalsessioncolPositionfloor = value.medicalsessioncolPositionfloor;
        this.medicalsessioncolPossitionward = value.medicalsessioncolPossitionward;
        this.medicalsessioncol_Possitionbad = value.medicalsessioncol_Possitionbad;
        this.positionbuildPositionbuildcolId = value.positionbuildPositionbuildcolId;
        this.doctorDoctorcolId = value.doctorDoctorcolId;
        this.statusStatuscolId = value.statusStatuscolId;
    }

    public Medicalsession(
        Integer       medicalsessioncolId,
        Integer       patientPatientcolId,
        LocalDateTime medicalsessioncolDateregistration,
        LocalDate     medicalsessioncolDateregistrationdown,
        String        medicalsessioncolDiagnoz,
        String        medicalsessioncolMedicaments,
        String        medicalsessioncolDiscriptions,
        Integer       medicalsessioncolPositionfloor,
        Integer       medicalsessioncolPossitionward,
        Integer       medicalsessioncol_Possitionbad,
        Integer       positionbuildPositionbuildcolId,
        Integer       doctorDoctorcolId,
        Integer       statusStatuscolId
    ) {
        this.medicalsessioncolId = medicalsessioncolId;
        this.patientPatientcolId = patientPatientcolId;
        this.medicalsessioncolDateregistration = medicalsessioncolDateregistration;
        this.medicalsessioncolDateregistrationdown = medicalsessioncolDateregistrationdown;
        this.medicalsessioncolDiagnoz = medicalsessioncolDiagnoz;
        this.medicalsessioncolMedicaments = medicalsessioncolMedicaments;
        this.medicalsessioncolDiscriptions = medicalsessioncolDiscriptions;
        this.medicalsessioncolPositionfloor = medicalsessioncolPositionfloor;
        this.medicalsessioncolPossitionward = medicalsessioncolPossitionward;
        this.medicalsessioncol_Possitionbad = medicalsessioncol_Possitionbad;
        this.positionbuildPositionbuildcolId = positionbuildPositionbuildcolId;
        this.doctorDoctorcolId = doctorDoctorcolId;
        this.statusStatuscolId = statusStatuscolId;
    }

    public Integer getMedicalsessioncolId() {
        return this.medicalsessioncolId;
    }

    public void setMedicalsessioncolId(Integer medicalsessioncolId) {
        this.medicalsessioncolId = medicalsessioncolId;
    }

    public Integer getPatientPatientcolId() {
        return this.patientPatientcolId;
    }

    public void setPatientPatientcolId(Integer patientPatientcolId) {
        this.patientPatientcolId = patientPatientcolId;
    }

    public LocalDateTime getMedicalsessioncolDateregistration() {
        return this.medicalsessioncolDateregistration;
    }

    public void setMedicalsessioncolDateregistration(LocalDateTime medicalsessioncolDateregistration) {
        this.medicalsessioncolDateregistration = medicalsessioncolDateregistration;
    }

    public LocalDate getMedicalsessioncolDateregistrationdown() {
        return this.medicalsessioncolDateregistrationdown;
    }

    public void setMedicalsessioncolDateregistrationdown(LocalDate medicalsessioncolDateregistrationdown) {
        this.medicalsessioncolDateregistrationdown = medicalsessioncolDateregistrationdown;
    }

    public String getMedicalsessioncolDiagnoz() {
        return this.medicalsessioncolDiagnoz;
    }

    public void setMedicalsessioncolDiagnoz(String medicalsessioncolDiagnoz) {
        this.medicalsessioncolDiagnoz = medicalsessioncolDiagnoz;
    }

    public String getMedicalsessioncolMedicaments() {
        return this.medicalsessioncolMedicaments;
    }

    public void setMedicalsessioncolMedicaments(String medicalsessioncolMedicaments) {
        this.medicalsessioncolMedicaments = medicalsessioncolMedicaments;
    }

    public String getMedicalsessioncolDiscriptions() {
        return this.medicalsessioncolDiscriptions;
    }

    public void setMedicalsessioncolDiscriptions(String medicalsessioncolDiscriptions) {
        this.medicalsessioncolDiscriptions = medicalsessioncolDiscriptions;
    }

    public Integer getMedicalsessioncolPositionfloor() {
        return this.medicalsessioncolPositionfloor;
    }

    public void setMedicalsessioncolPositionfloor(Integer medicalsessioncolPositionfloor) {
        this.medicalsessioncolPositionfloor = medicalsessioncolPositionfloor;
    }

    public Integer getMedicalsessioncolPossitionward() {
        return this.medicalsessioncolPossitionward;
    }

    public void setMedicalsessioncolPossitionward(Integer medicalsessioncolPossitionward) {
        this.medicalsessioncolPossitionward = medicalsessioncolPossitionward;
    }

    public Integer getMedicalsessioncol_Possitionbad() {
        return this.medicalsessioncol_Possitionbad;
    }

    public void setMedicalsessioncol_Possitionbad(Integer medicalsessioncol_Possitionbad) {
        this.medicalsessioncol_Possitionbad = medicalsessioncol_Possitionbad;
    }

    public Integer getPositionbuildPositionbuildcolId() {
        return this.positionbuildPositionbuildcolId;
    }

    public void setPositionbuildPositionbuildcolId(Integer positionbuildPositionbuildcolId) {
        this.positionbuildPositionbuildcolId = positionbuildPositionbuildcolId;
    }

    public Integer getDoctorDoctorcolId() {
        return this.doctorDoctorcolId;
    }

    public void setDoctorDoctorcolId(Integer doctorDoctorcolId) {
        this.doctorDoctorcolId = doctorDoctorcolId;
    }

    public Integer getStatusStatuscolId() {
        return this.statusStatuscolId;
    }

    public void setStatusStatuscolId(Integer statusStatuscolId) {
        this.statusStatuscolId = statusStatuscolId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Medicalsession other = (Medicalsession) obj;
        if (medicalsessioncolId == null) {
            if (other.medicalsessioncolId != null)
                return false;
        }
        else if (!medicalsessioncolId.equals(other.medicalsessioncolId))
            return false;
        if (patientPatientcolId == null) {
            if (other.patientPatientcolId != null)
                return false;
        }
        else if (!patientPatientcolId.equals(other.patientPatientcolId))
            return false;
        if (medicalsessioncolDateregistration == null) {
            if (other.medicalsessioncolDateregistration != null)
                return false;
        }
        else if (!medicalsessioncolDateregistration.equals(other.medicalsessioncolDateregistration))
            return false;
        if (medicalsessioncolDateregistrationdown == null) {
            if (other.medicalsessioncolDateregistrationdown != null)
                return false;
        }
        else if (!medicalsessioncolDateregistrationdown.equals(other.medicalsessioncolDateregistrationdown))
            return false;
        if (medicalsessioncolDiagnoz == null) {
            if (other.medicalsessioncolDiagnoz != null)
                return false;
        }
        else if (!medicalsessioncolDiagnoz.equals(other.medicalsessioncolDiagnoz))
            return false;
        if (medicalsessioncolMedicaments == null) {
            if (other.medicalsessioncolMedicaments != null)
                return false;
        }
        else if (!medicalsessioncolMedicaments.equals(other.medicalsessioncolMedicaments))
            return false;
        if (medicalsessioncolDiscriptions == null) {
            if (other.medicalsessioncolDiscriptions != null)
                return false;
        }
        else if (!medicalsessioncolDiscriptions.equals(other.medicalsessioncolDiscriptions))
            return false;
        if (medicalsessioncolPositionfloor == null) {
            if (other.medicalsessioncolPositionfloor != null)
                return false;
        }
        else if (!medicalsessioncolPositionfloor.equals(other.medicalsessioncolPositionfloor))
            return false;
        if (medicalsessioncolPossitionward == null) {
            if (other.medicalsessioncolPossitionward != null)
                return false;
        }
        else if (!medicalsessioncolPossitionward.equals(other.medicalsessioncolPossitionward))
            return false;
        if (medicalsessioncol_Possitionbad == null) {
            if (other.medicalsessioncol_Possitionbad != null)
                return false;
        }
        else if (!medicalsessioncol_Possitionbad.equals(other.medicalsessioncol_Possitionbad))
            return false;
        if (positionbuildPositionbuildcolId == null) {
            if (other.positionbuildPositionbuildcolId != null)
                return false;
        }
        else if (!positionbuildPositionbuildcolId.equals(other.positionbuildPositionbuildcolId))
            return false;
        if (doctorDoctorcolId == null) {
            if (other.doctorDoctorcolId != null)
                return false;
        }
        else if (!doctorDoctorcolId.equals(other.doctorDoctorcolId))
            return false;
        if (statusStatuscolId == null) {
            if (other.statusStatuscolId != null)
                return false;
        }
        else if (!statusStatuscolId.equals(other.statusStatuscolId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.medicalsessioncolId == null) ? 0 : this.medicalsessioncolId.hashCode());
        result = prime * result + ((this.patientPatientcolId == null) ? 0 : this.patientPatientcolId.hashCode());
        result = prime * result + ((this.medicalsessioncolDateregistration == null) ? 0 : this.medicalsessioncolDateregistration.hashCode());
        result = prime * result + ((this.medicalsessioncolDateregistrationdown == null) ? 0 : this.medicalsessioncolDateregistrationdown.hashCode());
        result = prime * result + ((this.medicalsessioncolDiagnoz == null) ? 0 : this.medicalsessioncolDiagnoz.hashCode());
        result = prime * result + ((this.medicalsessioncolMedicaments == null) ? 0 : this.medicalsessioncolMedicaments.hashCode());
        result = prime * result + ((this.medicalsessioncolDiscriptions == null) ? 0 : this.medicalsessioncolDiscriptions.hashCode());
        result = prime * result + ((this.medicalsessioncolPositionfloor == null) ? 0 : this.medicalsessioncolPositionfloor.hashCode());
        result = prime * result + ((this.medicalsessioncolPossitionward == null) ? 0 : this.medicalsessioncolPossitionward.hashCode());
        result = prime * result + ((this.medicalsessioncol_Possitionbad == null) ? 0 : this.medicalsessioncol_Possitionbad.hashCode());
        result = prime * result + ((this.positionbuildPositionbuildcolId == null) ? 0 : this.positionbuildPositionbuildcolId.hashCode());
        result = prime * result + ((this.doctorDoctorcolId == null) ? 0 : this.doctorDoctorcolId.hashCode());
        result = prime * result + ((this.statusStatuscolId == null) ? 0 : this.statusStatuscolId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Medicalsession (");

        sb.append(medicalsessioncolId);
        sb.append(", ").append(patientPatientcolId);
        sb.append(", ").append(medicalsessioncolDateregistration);
        sb.append(", ").append(medicalsessioncolDateregistrationdown);
        sb.append(", ").append(medicalsessioncolDiagnoz);
        sb.append(", ").append(medicalsessioncolMedicaments);
        sb.append(", ").append(medicalsessioncolDiscriptions);
        sb.append(", ").append(medicalsessioncolPositionfloor);
        sb.append(", ").append(medicalsessioncolPossitionward);
        sb.append(", ").append(medicalsessioncol_Possitionbad);
        sb.append(", ").append(positionbuildPositionbuildcolId);
        sb.append(", ").append(doctorDoctorcolId);
        sb.append(", ").append(statusStatuscolId);

        sb.append(")");
        return sb.toString();
    }
}
