/*
 * This file is generated by jOOQ.
 */
package ua.at.shegda.patientcards.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Positionbuild implements Serializable {

    private static final long serialVersionUID = 375367737;

    private Integer positionbuildcolId;
    private String  positionbuildcolName;

    public Positionbuild() {}

    public Positionbuild(Positionbuild value) {
        this.positionbuildcolId = value.positionbuildcolId;
        this.positionbuildcolName = value.positionbuildcolName;
    }

    public Positionbuild(
        Integer positionbuildcolId,
        String  positionbuildcolName
    ) {
        this.positionbuildcolId = positionbuildcolId;
        this.positionbuildcolName = positionbuildcolName;
    }

    public Integer getPositionbuildcolId() {
        return this.positionbuildcolId;
    }

    public void setPositionbuildcolId(Integer positionbuildcolId) {
        this.positionbuildcolId = positionbuildcolId;
    }

    public String getPositionbuildcolName() {
        return this.positionbuildcolName;
    }

    public void setPositionbuildcolName(String positionbuildcolName) {
        this.positionbuildcolName = positionbuildcolName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Positionbuild other = (Positionbuild) obj;
        if (positionbuildcolId == null) {
            if (other.positionbuildcolId != null)
                return false;
        }
        else if (!positionbuildcolId.equals(other.positionbuildcolId))
            return false;
        if (positionbuildcolName == null) {
            if (other.positionbuildcolName != null)
                return false;
        }
        else if (!positionbuildcolName.equals(other.positionbuildcolName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.positionbuildcolId == null) ? 0 : this.positionbuildcolId.hashCode());
        result = prime * result + ((this.positionbuildcolName == null) ? 0 : this.positionbuildcolName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Positionbuild (");

        sb.append(positionbuildcolId);
        sb.append(", ").append(positionbuildcolName);

        sb.append(")");
        return sb.toString();
    }
}
